apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-app
  template:
    metadata:
      labels:
        app: agent-app
    spec:
      containers:
      - name: streamlit
        image: localhost:32000/agent-app:latest
        imagePullPolicy: Always
        command: ["streamlit"]
        args: ["run", "app/Home.py", "--server.address", "0.0.0.0", "--server.port", "8501", "--server.baseUrlPath", "/"]
        ports:
        - containerPort: 8501
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: RUNTIME_ENV
          value: "dev"
        - name: DB_HOST
          value: "agent-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: DB_DATABASE
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: OPENAI_API_KEY
        - name: PHI_API_KEY
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: PHI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: agent-app
spec:
  selector:
    app: agent-app
  ports:
  - port: 8501
    targetPort: 8501
  type: ClusterIP
