apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-db
  template:
    metadata:
      labels:
        app: agent-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: agent-secrets
              key: DB_DATABASE
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: agent-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: agent-db
spec:
  selector:
    app: agent-db
  ports:
  - port: 5432
    targetPort: 5432
